apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-uulj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-uulj
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-uulj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-uulj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-uulj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-uulj@sha256:3b711c290b7f221afefb8f10173e9f143e6c663bc0b091fac8f11e463d58f928
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
