apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-uulj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-uulj@sha256:3b711c290b7f221afefb8f10173e9f143e6c663bc0b091fac8f11e463d58f928
        name: my-nodejs
        resources: {}
status: {}
